### ISSUE TITLE
[Bug] nil value error

### ISSUE THREAD

**Issue by malpertuis** [Alumian/CEPGP-Retail#94]
**The Error**
Date: 2019-10-24 23:44:21
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\cepgp\Utility.lua line 539:
   attempt to perform arithmetic on local 'GP' (a nil value)
Debug:
   cepgp\Utility.lua:539: CEPGP_rosterUpdate()
   cepgp\Core.lua:88: CEPGP_OnEvent()
   [string "*:OnEvent"]:1:
      [string "*:OnEvent"]:1
Locals:
event = "GUILD_ROSTER_UPDATE"
numGuild = 143
(for index) = 1
(for limit) = 143
(for step) = 1
i = 1
name = "Moveplz"
rank = "Social"
rankIndex = 9
_ = 41
class = "Warrior"
_ = "Swamp of Sorrows"
_ = "Main / ? / ? & ?"
officerNote = ""
online = true
_ = 1
classFileName = "WARRIOR"
EP = 0
GP = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = "Moveplz"
(*temporary) = nil
(*temporary) = nil
(*temporary) = 0
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on local 'GP' (a nil value)"

**Describe the bug**
I see this as soon as i log on. I turned all other addons off. Also cleared the saved variables. 

**To Reproduce**
Everytime i log on I see this

**Debug Information**
<details><summary>Debug Info</summary><br />
Version: 1.12.4<br />
GP Formula: (0.483x(1^<sup>((ilvl/26)+(rarity-4))</sup>)xSlot Modifier)x1<br />Base GP: 1<br />
Standby EP: False<br />
Standby Offline: False<br />
Standby Percent: 1<br />
Standby Accept Whispers: False<br />
Standby EP by Rank: True<br />
Standby EP Manual Delegation: False<br />
GUI for Loot: True<br />
Loot Response Keyphrase: need<br />
Standby EP Whisper Keyphrase: standby<br /><br />
<details><summary>Auto EP</summary>
</details>
<details><summary>EP Values</summary>
</details>
<details><summary>Standby Guild Ranks</summary>
</details>
<details><summary>Slot Weights</summary>
2HWEAPON: 2<br />
NECK: 0.5<br />
HEAD: 1<br />
HAND: 0.75<br />
WRIST: 0.5<br />
WEAPONMAINHAND: 1.5<br />
SHIELD: 0.5<br />
HOLDABLE: 0.5<br />
CLOAK: 0.5<br />
FEET: 0.75<br />
THROWN: 0.5<br />
TRINKET: 0.75<br />
RELIC: 0.5<br />
RANGEDRIGHT: 0.5<br />
WAIST: 0.75<br />
LEGS: 1<br />
CHEST: 1<br />
WEAPONOFFHAND: 0.5<br />
FINGER: 0.5<br />
RANGED: 0.5<br />
SHOULDER: 0.75<br />
</details>
<details><summary>Override List</summary>
</details>
<details><summary>Addons List</summary>
cepgp<br />
!Swatter<br />
</details>
<details><summary>Enabled Plugins</summary>
</details>
</details>

**Comment by malpertuis** [comment]
And I guess that because of this error i cant see other people version (or that they can see my version)
![image](https://user-images.githubusercontent.com/10599409/67528460-cff78a80-f6b9-11e9-9fbc-1d977be6ae2c.png)


This result in that I dont see the window show up when loot is distrubated

**Comment by Alumian** [comment]
Alright it looks like it's having an issue interpreting blank officer notes. Thought I fixed this, apparently not. I'll look into it.

**Comment by Alumian** [comment]
Try downloading the beta release I just posted and see if that helps.

**Comment by malpertuis** [comment]
@Alumian tnx for the quick response
I just tested out with the latest beta but I still get the same error:
`Count: 1
Message: ..\AddOns\cepgp\Utility.lua line 545:
   attempt to perform arithmetic on local 'GP' (a nil value)
Debug:
   cepgp\Utility.lua:545: CEPGP_rosterUpdate()
   cepgp\Core.lua:89: CEPGP_OnEvent()
   [string "*:OnEvent"]:1:
      [string "*:OnEvent"]:1
Locals:
event = "GUILD_ROSTER_UPDATE"
numGuild = 143
(for index) = 1
(for limit) = 143
(for step) = 1
i = 1
name = "Moveplz"
rank = "Social"
rankIndex = 9
_ = 41
class = "Warrior"
_ = "Badlands"
_ = "Main / ? / ? & ?"
officerNote = ""
online = true
_ = 0
classFileName = "WARRIOR"
EP = 0
GP = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = "Moveplz"
(*temporary) = nil
(*temporary) = nil
(*temporary) = 0
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on local 'GP' (a nil value)"

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  cepgp, v
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=5f)
`
Also got now also a second error when some1 whispers me:
`
Date: 2019-10-25 15:00:56
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\cepgp\Core.lua line 131:
   bad argument #1 to 'lower' (string expected, got nil)
Debug:
   [C]: lower()
   cepgp\Core.lua:131: CEPGP_OnEvent()
   [string "*:OnEvent"]:1:
      [string "*:OnEvent"]:1
Locals:
(*temporary) = nil
(*temporary) = "string expected, got nil"

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  cepgp, v
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=5f)
`

**Comment by Alumian** [comment]
Can you drop me a message on Discord pls?

**Comment by Alumian** [comment]
Spoke with Mal, we found that the folder they had was in all lowercase and because of that, the game wasn't initialising any globals or saved variables. Renamed the folder to all uppercase and the issue was resolved.
